name: Build a release
on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

env:
  STREAM: stable
jobs:
  Promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # if the job is re-ran to catch missed artifacts, allow updates
          generateReleaseNotes: true
#          artifacts: ${{ env.DIR_UPLOAD }}/*
          prerelease: false
          makeLatest: true
