name: Build and publish a release
on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

env:
  LATEST: false
jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Branch
        run: |
          mapfile -t branches < <(git branch -r --contains ${{ github.ref }} | awk '{print $1}')
          echo "${branches[@]}"
          for branch in "${branches[@]}"; do
            branch_name="${branch/origin\/}"
            echo "${branch_name}"
            if [ "${branch_name}" = 'main' ]; then
              echo LATEST=true >> $GITHUB_ENV
              break
            fi
          done

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # if the job is re-ran to catch missed artifacts, allow updates
          generateReleaseNotes: true
          prerelease: false
          makeLatest: ${{ fromJSON(env.LATEST) }}

  build-and-promote:
    needs: make-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v4

      - name: Set variables
        run: |
          GO_VERSION=$(grep -Eo "^go .*" go.mod | cut -d " " -f2)
          echo $GO_VERSION
          echo GO_VERSION=$GO_VERSION >> $GITHUB_ENV
          TAG=${GITHUB_REF##*/}
          echo $TAG
          echo TAG=$TAG >> $GITHUB_ENV
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          echo $REPO_NAME
          echo REPO_NAME=$REPO_NAME >> $GITHUB_ENV

      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: ${{ env.GO_VERSION }}
          pre_command: "rm -f go-*.tar.gz"
          build_command: "make ${{ env.REPO_NAME }}"
          release_tag: ${{ env.TAG }}
          md5sum: 'FALSE'
          sha256sum: 'TRUE'
