name: Build a pre-release
on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+a[0-9]+'
      - 'v?[0-9]+.[0-9]+.[0-9]+b[0-9]+'
      - 'v?[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
  workflow_dispatch:

env:
  STREAM: unstable
jobs:
  Promote:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # if the job is re-ran to catch missed artifacts, allow updates
          generateReleaseNotes: true
#          artifacts: ${{ env.DIR_UPLOAD }}/*
          prerelease: true
          makeLatest: false
